#!/usr/bin/env php
<?php

use Ever2BoostPHP\Command\Ever2BoostPHP;
use Symfony\Component\Console\Application;

/* @see https://github.com/sebastianbergmann/phpunit/blob/master/phpunit */
foreach ([__DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php', __DIR__.'/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}

require PHPUNIT_COMPOSER_INSTALL;

$command = new Ever2BoostPHP();
$application = new Application(Ever2BoostPHP::class, Ever2BoostPHP::VERSION);
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();
